apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  namespace: netology-1-4
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.25-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
              readOnly: true
      volumes:
        - name: html
          configMap:
            name: web-index
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multitool-deploy
  namespace: netology-1-4
spec:
  replicas: 3
  selector:
    matchLabels:
      app: multitool
  template:
    metadata:
      labels:
        app: multitool
    spec:
      containers:
        - name: multitool
          image: wbitt/network-multitool:alpine-minimal
          env:
            - name: HTTP_PORT
              value: "8080"
          ports:
            - containerPort: 8080
