apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: netology-1-4
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
    - name: http-nginx
      port: 9001
      targetPort: 80
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: multitool-svc
  namespace: netology-1-4
spec:
  type: ClusterIP
  selector:
    app: multitool
  ports:
    - name: http-multitool
      port: 9002
      targetPort: 8080
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
  namespace: netology-1-4
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - name: http-nginx
      port: 80
      targetPort: 80
      nodePort: 30080
      protocol: TCP
